apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"author":"ZAFAR","project":"practice"},"name":"nginx1","namespace":"s-37"},"spec":{"containers":[{"image":"nginx","name":"nginx-container"}]}}
    creationTimestamp: "2024-01-08T15:26:40Z"
    labels:
      author: ZAFAR
      project: practice
    name: nginx1
    namespace: s-37
    resourceVersion: "4031462"
    uid: 84bc833c-2c6e-43b3-84bd-c9bf33ed27eb
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx-container
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-bkpkl
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: node4
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-bkpkl
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-08T15:26:40Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-08T15:26:42Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-08T15:26:42Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-08T15:26:40Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://6b61185cf1afec680b6674a19ecc469e53ecb5288bad514c3bc5009d448c036d
      image: docker.io/library/nginx:latest
      imageID: docker.io/library/nginx@sha256:2bdc49f2f8ae8d8dc50ed00f2ee56d00385c6f8bc8a8b320d0a294d9e3b49026
      lastState: {}
      name: nginx-container
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-08T15:26:41Z"
    hostIP: 95.217.135.101
    phase: Running
    podIP: 10.233.65.202
    podIPs:
    - ip: 10.233.65.202
    qosClass: BestEffort
    startTime: "2024-01-08T15:26:40Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"author":"ZAFAR","project":"practice"},"name":"nginx2","namespace":"s-37"},"spec":{"containers":[{"image":"nginx","name":"nginx-container"}]}}
    creationTimestamp: "2024-01-08T15:26:41Z"
    labels:
      author: ZAFAR
      project: practice
    name: nginx2
    namespace: s-37
    resourceVersion: "4031466"
    uid: 7ddcb2d0-fd1d-4e2e-b995-d7aec45befe6
  spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx-container
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-2p5ws
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: node3
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-2p5ws
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-01-08T15:26:41Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-01-08T15:26:42Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-01-08T15:26:42Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-01-08T15:26:41Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://427ce00571b11711105dffd5445693abee975d5f32fff4bc3017d92a34555482
      image: docker.io/library/nginx:latest
      imageID: docker.io/library/nginx@sha256:2bdc49f2f8ae8d8dc50ed00f2ee56d00385c6f8bc8a8b320d0a294d9e3b49026
      lastState: {}
      name: nginx-container
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-01-08T15:26:42Z"
    hostIP: 65.109.14.160
    phase: Running
    podIP: 10.233.68.169
    podIPs:
    - ip: 10.233.68.169
    qosClass: BestEffort
    startTime: "2024-01-08T15:26:41Z"
kind: List
metadata:
  resourceVersion: ""
