apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-app
  template:
    metadata:
      labels:
        app: hr-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.18
